"""Shared interpretation instructions for the reviewed-Question outcome."""
QUESTION_REVIEW_GUIDANCE = """
- open_question: use only when this Evidence raises a specific consequential unresolved concern worth tracking, but does not establish a Current State change. The decision_question MUST be the exact concise Question text to track (at most 500 characters). Supply no proposed_changes, affected_state_item_ids, or resolves_question_ids. Human acceptance creates a normal, non-blocking open Question; never create it directly or infer blocking.
- Check open_questions and Current State before opening a Question. If either already says a target is unknown/not established and Evidence only repeats that, preserve only. A narrower unknown or new decision need may be distinct. If Evidence answers an open Question, use resolves_question_ids.
- Lower-authority disagreement matching Current State opens no Question.
- Partial answers leave broader Questions open; do not widen scope. Use resolves_question_ids only when Evidence settles the whole Question. Slack approved for #product/#support while other channels remain under review updates scoped State but does not resolve an all-channels Question.
- A narrower, more concrete variant of an existing open Question is a distinct Question worth tracking, not a reason to stay silent. Example: an existing open Question broadly asks what evidence would justify reconsidering a safety boundary (e.g. human review). New Evidence showing a decision-making authority specifically floating removing that boundary for one narrow sub-case (e.g. only low-risk password-reset answers) is a new, more concrete signal -- even though it does not resolve the broader existing Question and even though Evidence also says the change was not approved. "Related to an existing Question" is not the same as "the same unknown"; do not silently drop Evidence just because its topic overlaps a Question already being tracked.
- Do not turn routine missing detail, speculative possibilities, or every observation into a Question. Explain the concrete consequence in why_consequential. A suspicion is not an established fact, and a confirmed fact should not be downgraded into a Question.
- Example: credible observations suggest agents approve AI drafts without checking them, but do not establish that as a fact. Suggest: Are support agents meaningfully reviewing AI-generated drafts before approval? Do not claim human review was removed or automatically mark the concern blocking.
- Keep the existing Review types for established changes, new facts, and risks to maintained understanding. Use open_question for tracking an unknown, not as a substitute for a supported State change.
"""
