window.PROJECT_CONTEXT_DATA = {
  project: {
    name: 'Northstar',
    stage: 'Late discovery · implementation planning next',
    description: 'A support-AI discovery project that has narrowed to a reviewed Tier 1 troubleshooting assistant. Most core discovery is complete; the team is resolving the remaining security, access-authority, and evaluation questions before implementation planning.',
    outcome: 'Reduce repetitive support effort without sacrificing response quality or human control',
    status: 'Discovery is nearly complete. Tier 1 troubleshooting with human review is the working pilot direction; several implementation-critical questions remain open.'
  },
  knowledge: [
    {id:'k-pilot', title:'Pilot direction', topics:['automation','scope'], statement:'The first pilot is focused on Tier 1 troubleshooting assistance. AI drafts and assembles context; a support rep reviews before anything customer-facing is sent.', support:['n-scope','n-workflow'], state:'current'},
    {id:'k-autonomy', title:'Autonomy target', topics:['automation','success-metrics'], statement:'Leadership has asked whether 50% autonomous resolution is achievable, but discovery has not established a safe automation percentage and the first implementation is still human-reviewed.', support:['n-leadership-followup'], state:'current'},
    {id:'k-access', title:'Feature access check', topics:['feature-access'], statement:'Standard plan rules are used as one troubleshooting input when checking feature access.', support:['n-access-map'], state:'current', afterReview:'Plan rules alone are insufficient to determine effective customer feature access because account-level exceptions exist.'},
    {id:'k-security', title:'Human review boundary', topics:['security','automation'], statement:'Human review remains required for the pilot. Security wants agreed high-risk failure categories and evidence across them before that boundary is reconsidered.', support:['n-security-workshop'], state:'current'},
    {id:'k-eval', title:'Evaluation direction', topics:['success-metrics'], statement:'The pilot will be evaluated with a combination of response-time improvement, reviewer edits, escalation behavior, unsupported-claim checks, and failure severity rather than a single automation metric.', support:['n-eval-session'], state:'current'},
    {id:'k-data', title:'Data boundary', topics:['security','data'], statement:'The pilot should use the minimum customer and account data needed for troubleshooting, remain read-only, and avoid account-changing actions in the first implementation.', support:['n-data-flow','n-scope'], state:'current'},
    {id:'k-training', title:'Rep enablement', topics:['operations'], statement:'Rep training will be task-based: when to use the assistant, what still requires manual verification, how to inspect support for an answer, and how to flag a bad suggestion.', support:['n-training'], state:'current'}
  ],
  notes: [
    {id:'n-kickoff', title:'Pilot kickoff — rough notes', text:'Goal for discovery: figure out whether an AI assistant can take some of the repetitive reading/searching out of Tier 1 without turning the first pilot into an autonomous support bot. Support called out password/login troubleshooting, plan questions, setup questions, and “where is this setting?” as common work. Account changes, billing adjustments, ownership changes, refunds, and anything security-sensitive are out for now. One useful point from the meeting: ticket labels are not clean enough to define scope by themselves. We need representative examples and edge cases, not just volume counts. Follow-ups: workflow walkthrough with Support; collect 20–30 representative tickets; Security intro; ask vendor what data is retained in the sandbox.', source:'Pilot kickoff', date:'Aug 18', topics:['automation','security','scope'], status:'accepted'},
    {id:'n-ticket-sample', title:'Representative ticket review', text:'Reviewed a small set of recent Tier 1 examples with two reps. The easiest cases were not necessarily the shortest tickets; they were the ones where the answer could be grounded in a stable help-center article and did not depend on account-specific exceptions. Access questions were deceptively difficult because the customer’s nominal plan did not always match what the rep saw in the account. Password/login issues split into “explain the normal steps” versus “change or override something,” which should probably be treated as different risk classes. We also found several tickets where the final answer came from an internal Slack thread because the public/internal docs had not caught up with a recent release.', source:'Ticket review working session', date:'Aug 19', topics:['automation','feature-access','security'], status:'accepted'},
    {id:'n-workflow', title:'Tier 1 workflow walkthrough', text:'Sat with a Support lead through the normal troubleshooting path. Rep starts in the queue, reads the ticket, checks account context, searches the help center/internal docs, then looks at prior tickets if the documented path does not fit. Experienced reps sometimes know immediately which account detail matters; newer reps spend more time figuring out what to trust. Escalation is not always “this is technically hard.” A lot of it is “I cannot verify which state is authoritative.” That distinction matters for the pilot: retrieval can make information easier to find without solving authority. Working idea is still assistive: AI can summarize context and draft a response, rep checks it and sends.', source:'Support workflow walkthrough', date:'Aug 20', topics:['automation','feature-access','operations'], status:'accepted'},
    {id:'n-contact', title:'Vendor coordination / contacts', text:'Maya Chen — Solutions Support. Shared pilot thread for routine questions. Thursday 10:00 AM check-in. Read-only pilot confirmed; no account-write permissions.', source:'Vendor coordination', date:'Aug 21', topics:['vendor','operations','security'], status:'accepted'},
    {id:'n-data-flow', title:'Security prep — data flow questions', text:'Prep for Security review. Current proposed flow is: ticket text + selected account context → prompt assembly → model/vendor → draft answer back to the support workspace. Need to be precise about which account fields are actually required; “give it the whole account” is not acceptable as a requirement. Questions for vendor/Security: retention for prompts and outputs, whether customer data is used for model training, sub-processors, where logs live, and whether we can redact obvious secrets/credentials before the model call. For the pilot, keep it read-only and do not expose tools that can modify customer records. Also need a decision on whether internal Slack content is eligible as retrieval material; current answer should probably be no until ownership/freshness is clearer.', source:'Security prep notes', date:'Aug 21', topics:['security','data','feature-access'], status:'accepted'},
    {id:'n-eval-session', title:'Evaluation working session', text:'We do not want “tickets touched by AI” or raw automation rate to be the success metric. Working scorecard: first-response-time improvement on in-scope tickets; reviewer edit rate; severity of edits (cosmetic vs factual/policy); escalation rate; unsupported-claim checks on a sample; and re-contact/reopen signal if we can get it without building extra reporting. A fast draft that needs a major correction is not a win. We should establish baseline examples before implementation and keep a small set of known edge cases as regression checks. Exact pass thresholds are still open. Security specifically wants high-risk failures separated from average quality so a good mean score cannot hide one unacceptable class of error.', source:'Evaluation working session', date:'Aug 22', topics:['success-metrics','automation','security'], status:'accepted'},
    {id:'n-training', title:'Rep training planning', text:'Keep enablement short and task-based. Proposed 30-minute session: what the assistant is for, in/out-of-scope examples, how to inspect support for a draft, what still needs manual verification, and how to flag a bad suggestion. Support wants a few “looks plausible but is wrong” examples. Feedback capture is still unresolved; use the existing QA process if possible.', source:'Training planning', date:'Aug 23', topics:['operations','security'], status:'accepted'},
    {id:'n-slack', title:'Slack follow-up — documentation gaps', text:'Quick follow-up: docs sometimes lag releases, so reps check Slack. Useful evidence, but not automatically authoritative. Leave it out of v1 retrieval.', source:'Support Slack follow-up', date:'Aug 23', topics:['feature-access','security','data'], status:'accepted'},
    {id:'n-scope', title:'Pilot scope v2', text:'Scope is now narrow enough to take into implementation planning. In scope: Tier 1 troubleshooting where the assistant can ground a draft in approved support material and available read-only account context. Examples: standard login troubleshooting, setup/how-to, locating a setting, explaining documented plan behavior. Out: refunds/billing changes, account ownership changes, credential resets that require an action, security-sensitive changes, exceptions that require judgment, and anything the rep cannot verify from an approved source. Human review remains required before a customer-facing response. This is intentionally conservative for the first evaluation cycle.', source:'Scope draft', date:'Aug 24', topics:['automation','security','scope'], status:'accepted'},
    {id:'n-access-map', title:'Feature-access troubleshooting map', text:'Access check today: plan matrix first, account details when reality does not match. Treat the matrix as a useful starting point, not final authority. Still need to resolve temporary entitlements, grandfathered packages, and sales exceptions.', source:'Discovery synthesis', date:'Aug 24', topics:['feature-access','automation'], status:'accepted'},
    {id:'n-security-workshop', title:'Security discovery workshop', text:'Security is comfortable with an assistive/read-only pilot in principle, provided the team is explicit about the data path, keeps consequential account actions out, and defines unacceptable failure categories before launch. Categories discussed: exposing data from the wrong customer/account, giving instructions that weaken account security, confidently asserting an entitlement the customer does not have, and fabricating a support policy or exception. Human review stays in place. Security does not want a leadership automation target used as evidence that review can be removed. Before reconsidering that boundary, they want evaluation evidence across the agreed high-risk categories and a clear escalation path when the assistant cannot ground an answer. No safe autonomy percentage was established.', source:'Security discovery', date:'Aug 25', topics:['security','automation','data','feature-access'], status:'accepted'},
    {id:'n-leadership', title:'Leadership check-in — notes', text:'Leadership wants the pilot to show a visible productivity result and asked whether 50% autonomous ticket resolution in roughly six weeks could be a useful north-star target. We pushed back on turning that into a delivery commitment during discovery. Current framing: first prove that the assistant can reduce handling effort on a bounded Tier 1 set while maintaining quality and human review. Autonomy can be evaluated later if the evidence supports it. Leadership was fine with keeping 50% as an aspirational question rather than a success criterion for implementation.', source:'Leadership discussion', date:'Aug 25', topics:['automation','success-metrics'], status:'accepted'},
    {id:'n-implementation-readiness', title:'Implementation-readiness check', text:'Discovery feels close to done. We have a bounded pilot use case, a conservative permission model, an initial data-flow sketch, a working evaluation approach, and a training outline. The remaining items are mostly decisions rather than broad discovery: confirm authoritative feature-access source; turn Security’s high-risk categories into test cases; set practical evaluation thresholds; confirm vendor retention/no-training terms for the sandbox; decide where rep feedback is recorded. Once those are resolved, Product can turn this into an implementation backlog without another open-ended discovery phase.', source:'Product working notes', date:'Aug 26', topics:['operations','security','feature-access','success-metrics'], status:'accepted'},
    {id:'n-support', title:'Senior Support Rep interview — access exceptions', text:'Rep walked through three recent access cases where the normal plan matrix did not tell the whole story. One customer had temporary access enabled during a migration, one was on a grandfathered package, and one had an exception added during a commercial escalation. In all three cases, the rep checked account-level details before answering. Their wording was basically: “plan is where I start, but it is not always what the customer actually has.” They were not sure which backend field should be considered authoritative across every exception type and said they sometimes ask Billing/CS to confirm edge cases. This challenges the assumption that standard plan rules are sufficient for access troubleshooting, but it does not identify a single replacement source.', source:'Senior Support Rep interview', date:'Aug 26', topics:['feature-access','security','automation'], status:'pending', reviewId:'r-access'},
    {id:'n-leadership-followup', title:'Leadership follow-up', text:'Human-reviewed first release is fine. Leadership wants the weekly update to separate decided / open / implementation risks. No new numeric target. 50% autonomy remains aspirational, not a requirement.', source:'Leadership follow-up', date:'Aug 26', topics:['automation','success-metrics','operations'], status:'accepted'},
    {id:'n-vendor-security', title:'Vendor security questionnaire — notes', text:'Maya sent responses for the sandbox configuration. Read-only integration is supported. Vendor says customer content is not used to train the underlying model under the proposed enterprise terms; retention and sub-processor language still need Security/Legal to confirm against the actual agreement rather than relying on the call summary. They can expose request logs for troubleshooting, but we need to decide what we actually want logged because full prompt logging could itself retain customer data. Open item: confirm deletion/retention window and whether redaction happens before or after vendor logging.', source:'Vendor security follow-up', date:'Aug 27', topics:['security','data','vendor'], status:'accepted'},
    {id:'n-security-followup', title:'Security follow-up — evaluation gate', text:'Security clarified the review-removal question. They are not asking for a particular automation percentage. Their gate is evidence: the pilot has to be tested across the agreed high-risk failure categories, failures have to be classified by severity, and the team needs an explicit threshold for any launch-blocking category. Even if average answer quality is high, a material wrong-account/data-exposure failure would block expansion. This establishes what evidence Security wants before reconsidering human review; it does not establish that the threshold has been met or that review should actually be removed.', source:'Security follow-up', date:'Aug 27', topics:['security','automation','success-metrics'], status:'pending', reviewId:'r-security'},
    {id:'n-test-cases', title:'Eval case-writing session', text:'Started turning discovery into representative test cases. Current buckets: straightforward documented how-to; ambiguous customer wording; plan/access mismatch; stale documentation; login troubleshooting; request that drifts into an account-changing action; unsupported exception request; and “not enough evidence” cases where the correct behavior is to escalate instead of drafting a confident answer. We intentionally included cases where the likely answer is easy but the authority is weak. Need 5–10 examples per bucket before implementation QA. Security’s high-risk categories still need to be mapped into explicit launch-blocking cases once the pending follow-up is reviewed.', source:'Evaluation case-writing', date:'Aug 28', topics:['success-metrics','security','automation','feature-access'], status:'accepted'},
    {id:'n-weekly', title:'Friday project update — discovery almost complete', text:'Discovery is nearing completion. This week we finalized the narrow Tier 1 / human-reviewed pilot scope, sketched the read-only data path, aligned on a multi-signal evaluation approach, and started representative test cases. The biggest unresolved implementation item is feature-access authority: plan rules are useful, but new Support evidence suggests account-level exceptions matter and that evidence is waiting for review. Security also sent a more concrete evidence gate for any future reconsideration of human review; that follow-up is waiting for review as well. Next useful work is not more broad discovery: review those two items, confirm vendor retention terms, finish high-risk eval cases, and turn the settled discovery into an implementation backlog.', source:'Weekly project update', date:'Aug 28', topics:['automation','security','feature-access','success-metrics','operations'], status:'accepted'},
    {id:'n-handoff', title:'Implementation planning handoff — draft outline', text:'Drafting the handoff for implementation planning. Proposed build order: 1) approved knowledge/document retrieval; 2) read-only account context with field allowlist; 3) draft response + source display; 4) human review/send flow; 5) feedback capture using the existing QA process if possible; 6) evaluation logging. Dependencies before backlog is final: authoritative feature-access source, Security review of vendor retention terms, agreed launch-blocking eval cases. Deliberately not included in v1: autonomous sends, account write actions, Slack ingestion, Jira/GitHub integrations, or automated escalation routing.', source:'Product handoff draft', date:'Aug 29', topics:['operations','security','data','feature-access','scope'], status:'accepted'}
  ],
  questions: [
    {id:'q-suitable', text:'Which troubleshooting cases are actually suitable for the first pilot?', topics:['automation','scope'], status:'open', origin:'Initial discovery', created:'Aug 19'},
    {id:'q-review', text:'What evidence would justify reconsidering human review?', topics:['security','automation'], status:'open', origin:'Security discovery', created:'Aug 25'},
    {id:'q-authority-seed', text:'What source authoritatively determines effective customer feature access?', topics:['feature-access','security'], status:'open', origin:'Access mapping', created:'Aug 24'},
    {id:'q-thresholds', text:'What evaluation thresholds should block or allow pilot launch?', topics:['success-metrics','security'], status:'open', origin:'Evaluation working session', created:'Aug 22'},
    {id:'q-retention', text:'What retention/deletion terms will apply to pilot prompts and outputs?', topics:['security','data','vendor'], status:'open', origin:'Vendor security review', created:'Aug 27'}
  ],
  reviews: [
    {
      id:'r-access', evidenceId:'n-support', topics:['feature-access','security'], status:'pending',
      title:'New evidence weakens the current access assumption',
      summary:'The current troubleshooting model starts from standard plan rules. The Support interview documents temporary, grandfathered, and commercial exceptions, so plan tier alone cannot reliably represent effective access.',
      proposed:'Plan rules alone are insufficient to determine effective customer feature access because account-level exceptions exist.',
      unresolved:'Which account-level source or field should be authoritative across exception types.',
      current:'Standard plan rules are used as one troubleshooting input when checking feature access.',
      evidence:'A Senior Support Rep walked through recent temporary-access, grandfathered, and commercial-exception cases that did not match the normal plan matrix.',
      establishes:'Real account-level exceptions exist, so the plan matrix is not sufficient by itself.',
      doesNot:'It does not establish a single replacement source or prove that any specific backend field is authoritative.',
      resolvesQuestionId:'q-authority-seed'
    },
    {
      id:'r-security', evidenceId:'n-security-followup', topics:['security','automation','success-metrics'], status:'pending',
      title:'Security made the review boundary more operational',
      summary:'The earlier understanding was that Security needed to define unacceptable failures before human review could be reconsidered. The follow-up now specifies an evidence gate across agreed high-risk categories and launch-blocking severity thresholds.',
      proposed:'Human review may only be reconsidered after evaluation across agreed high-risk failure categories with explicit launch-blocking thresholds.',
      unresolved:'Whether the eventual pilot evidence will meet that gate, and whether meeting it would actually justify removing review.',
      current:'Human review remains required; Security wants unacceptable failure categories defined before that boundary is reconsidered.',
      evidence:'Security specified category-level testing, severity classification, and explicit launch-blocking thresholds rather than a target automation percentage.',
      establishes:'A concrete evidence requirement for any future reconsideration of human review.',
      doesNot:'It does not establish that human review should be removed, that the evidence threshold has been met, or that any percentage of tickets is safe to automate.',
      resolvesQuestionId:'q-review'
    }
  ],
  history: [
    {id:'h0', date:'Aug 24', type:'Current understanding established', before:'Broad AI support pilot', after:'Tier 1 troubleshooting assistance became the leading direction, with human review and no account-changing actions.', reason:'Discovery synthesis', decision:'Team synthesis'},
    {id:'h1', date:'Aug 25', type:'Request recorded without becoming truth', before:'No numeric autonomy target', after:'Leadership asked about 50% autonomy; the request remained distinct from an implementation commitment.', reason:'Leadership discussion', decision:'Preserved as a request'},
    {id:'h2', date:'Aug 28', type:'Discovery phase narrowed', before:'Open-ended discovery', after:'Remaining work is implementation-readiness decisions and test definition rather than broad problem discovery.', reason:'Weekly project update', decision:'Product synthesis'}
  ],
  aiScenarios: [
    {id:'access', family:'answer', topics:['feature-access'], aliases:['what determines feature access','how are we determining customer access','how do we know what features a customer has','what decides plan access','customer feature access','feature access','plan access','what determines customer feature access','what did we decide about pilot access'], output:'answer'},
    {id:'automation', family:'unresolved', topics:['automation'], aliases:['what percentage can we safely automate','how much can we automate','what percent can be automated','what portion can ai handle','how much troubleshooting is safe to automate','automation percentage','safe automation share','what share of tickets can be automated'], output:'unknown'},
    {id:'security', family:'meeting', topics:['security','data','feature-access'], aliases:['prepare me for security meeting','prepare for security meeting','help me get ready for the security meeting','meeting with security','security briefing','what should i know before i talk to security','get me ready for security','brief me for security','what do i need to know for security','catch me up before security','i have a security meeting','can you prep me for my meeting'], output:'meeting'},
    {id:'weekly', family:'summary', topics:['automation','security','feature-access','success-metrics','operations'], aliases:['give me a weekly summary','weekly summary','generate weekly summary','summarize what changed this week','weekly project summary','weekly project update','status summary for project contacts','weekly summary for project client contacts','weekly status update'], output:'summary'},
    {id:'changed', family:'change', topics:['feature-access','automation','security','operations'], aliases:['what changed this week','what changed','recent changes','what is new','show me recent changes','did anything important change','anything new since last week'], output:'change'},
    {id:'leadership', family:'draft', topics:['automation','security','feature-access','operations'], aliases:['draft an update for leadership','turn this into an exec update','write a leadership update','draft executive update','write an update for leadership','what should i tell leadership','write something i can send my boss'], output:'draft'},
    {id:'support-update', family:'draft', topics:['automation','operations'], aliases:['write a short status update for the support team','draft a support team update','write a slack update for support','turn this into a slack update'], output:'support-draft'},
    {id:'waiting', family:'unresolved-list', topics:['automation','security','feature-access','success-metrics','data'], aliases:['what are we still waiting on','what do we not know yet','what dont we know yet','open questions','what is unresolved','what are the unknowns','what needs to be resolved before implementation'], output:'questions'},
    {id:'contact', family:'answer', topics:['vendor','operations'], aliases:['who is my support rep contact','who is my support contact','who is the vendor contact','who do i contact for vendor support','support rep contact','vendor support rep','who is maya'], output:'contact'},
    {id:'pilot-start', family:'answer', topics:['operations','scope'], aliases:['when does the pilot start','pilot start date','when are we starting the pilot','are we ready to implement','are we ready for implementation'], output:'pilot-start'},
    {id:'retrieve-access', family:'retrieve', topics:['feature-access'], aliases:['find notes about plan access','show me what we have on plan access','find feature access notes','notes about feature access','show notes on customer access'], output:'retrieve'}
  ],
  sampleInformation: 'Senior Support Rep: The plan matrix is where I start, but it does not always reflect what the customer actually has. Temporary entitlements and grandfathered packages are the two cases I see most often.'
};
